on:
  push:
    branches:
      - master

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn install
      - name: Publish Release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          yarn deploy:patch
