on:
  push:
    branches:
      - master

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn install
      - name: Build webapp
        run: yarn build-webapp
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: asd
          registryUrl: https://marketplace.visualstudio.com
          dryRun: true
