on:
  push:
    branches:
      - master

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yarn install
        run: yarn install
      - name: Build webapp
        run: yarn build-webapp
      - name: Publish Release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          git config --global user.name mcdev
          git config --global user.email "username@users.noreply.github.com"
          yarn deploy:patch
          git push
          git push --tags
